# Generated by Django 5.2.15 on 2026-07-02 02:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_preregisteredapplicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamVenueConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100, unique=True, verbose_name='Region')),
                ('venue_name', models.CharField(blank=True, max_length=500, verbose_name='Venue Name')),
                ('exam_date', models.DateTimeField(blank=True, null=True, verbose_name='Exam Date & Time')),
            ],
            options={
                'verbose_name': 'Exam Venue Config',
                'verbose_name_plural': 'Exam Venue Configs',
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_domain', models.CharField(default='id.akhu.uz', max_length=255, verbose_name='QR Code Domain')),
                ('permits_released', models.BooleanField(default=False, verbose_name='Permits Released')),
                ('permit_release_date', models.DateField(blank=True, null=True, verbose_name='Permit Release Date')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.RemoveField(
            model_name='preregisteredapplicant',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='preregisteredapplicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='preregisteredapplicant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='preregisteredapplicant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='preregisteredapplicant',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='applicant_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Applicant ID'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='exam_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Exam Date & Time'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='exam_venue',
            field=models.CharField(blank=True, max_length=500, verbose_name='Exam Venue'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='program',
            field=models.CharField(blank=True, max_length=200, verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='selected_region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Selected Region'),
        ),
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='applicant_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Applicant ID'),
        ),
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='given_name',
            field=models.CharField(default='', max_length=100, verbose_name='Given Name'),
        ),
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='program',
            field=models.CharField(blank=True, max_length=200, verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='surname',
            field=models.CharField(default='', max_length=100, verbose_name='Surname'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='preregisteredapplicant',
            name='passport_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Card / Passport Number'),
        ),
    ]
