# Generated by Codex on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_examvenueconfig_systemsetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='passports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='passport_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Region'),
        ),
    ]
