# Generated by Django 5.2.15 on 2026-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_preregisteredapplicant_passport_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregisteredapplicant',
            name='passport_embedding',
        ),
        migrations.RemoveField(
            model_name='preregisteredapplicant',
            name='passport_image',
        ),
    ]
