# Generated by Codex on 2026-07-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_preregisteredapplicant_passport_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='passports/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='preregisteredapplicant',
            name='passport_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
