# Generated by Django 5.2.15 on 2026-07-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restore_preregistered_passport_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='passport_image',
            field=models.ImageField(blank=True, null=True, upload_to='passports/%Y/%m/', verbose_name='Passport / ID Image'),
        ),
        migrations.AddField(
            model_name='examvenueconfig',
            name='location_link',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Location Link'),
        ),
    ]
