# Generated by Django 5.2.15 on 2026-07-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_applicantprofile_passport_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='arrival_time',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Arrival Time'),
        ),
        migrations.AddField(
            model_name='examvenueconfig',
            name='arrival_time',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Arrival Time'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='exam_date',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Exam Date & Time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('supervisor', 'Supervisor'), ('admin', 'Administrator'), ('exam_staff', 'Exam Staff')], default='applicant', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='examvenueconfig',
            name='exam_date',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Exam Date & Time'),
        ),
    ]
