# Generated by Django 5.0.6 on 2026-06-24 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=255)),
                ('current_step', models.IntegerField(choices=[(1, 'Personal Information'), (2, 'Document Upload'), (3, 'Face Capture'), (4, 'Liveness Detection'), (5, 'Face Matching'), (6, 'Completed')], default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('review_required', 'Review Required'), ('rejected', 'Rejected')], default='in_progress', max_length=20)),
                ('verification_type', models.CharField(choices=[('initial', 'Initial Verification'), ('exam_day', 'Examination Day'), ('re_verification', 'Re-Verification')], default='initial', max_length=20)),
                ('step_personal_info_done', models.BooleanField(default=False)),
                ('step_document_done', models.BooleanField(default=False)),
                ('step_face_capture_done', models.BooleanField(default=False)),
                ('step_liveness_done', models.BooleanField(default=False)),
                ('step_matching_done', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Session',
                'verbose_name_plural': 'Verification Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('initial', 'Initial Verification'), ('exam_day', 'Examination Day'), ('re_verification', 'Re-Verification')], max_length=20)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('review_required', 'Review Required'), ('rejected', 'Rejected')], max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_info', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='accounts.applicantprofile')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_verifications', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='verification.verificationsession')),
            ],
            options={
                'verbose_name': 'Verification Log',
                'verbose_name_plural': 'Verification Logs',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='LivenessChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_type', models.CharField(choices=[('blink', 'Blink'), ('look_left', 'Look Left'), ('look_right', 'Look Right'), ('look_up', 'Look Up')], max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liveness_challenges', to='verification.verificationsession')),
            ],
            options={
                'verbose_name': 'Liveness Challenge',
                'verbose_name_plural': 'Liveness Challenges',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passport_image', models.ImageField(blank=True, null=True, upload_to='passports/%Y/%m/')),
                ('passport_image_hash', models.CharField(blank=True, max_length=64)),
                ('selfie_image', models.ImageField(blank=True, null=True, upload_to='selfies/%Y/%m/')),
                ('selfie_image_hash', models.CharField(blank=True, max_length=64)),
                ('passport_embedding', models.JSONField(blank=True, null=True)),
                ('selfie_embedding', models.JSONField(blank=True, null=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('match_percentage', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('verified', 'Verified'), ('review_required', 'Review Required'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('liveness_passed', models.BooleanField(blank=True, null=True)),
                ('anti_spoof_score', models.FloatField(blank=True, null=True)),
                ('anti_spoof_result', models.CharField(blank=True, max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profiles', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_profile', to='verification.verificationsession')),
            ],
            options={
                'verbose_name': 'Face Profile',
                'verbose_name_plural': 'Face Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
