# Generated by Django 5.2.15 on 2026-06-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faceprofile',
            name='selfie_left',
            field=models.ImageField(blank=True, null=True, upload_to='liveness/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='faceprofile',
            name='selfie_right',
            field=models.ImageField(blank=True, null=True, upload_to='liveness/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='faceprofile',
            name='selfie_up',
            field=models.ImageField(blank=True, null=True, upload_to='liveness/%Y/%m/'),
        ),
    ]
