# Generated by Django 5.2.15 on 2026-07-03 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_preregisteredapplicant_passport_reference'),
        ('verification', '0002_faceprofile_selfie_left_faceprofile_selfie_right_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='faceprofile',
            index=models.Index(fields=['status'], name='faceprofile_status_idx'),
        ),
        migrations.AddIndex(
            model_name='faceprofile',
            index=models.Index(fields=['session', 'status'], name='faceprofile_session_status_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['verified_at'], name='vlog_verified_at_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['applicant_profile', 'verification_type'], name='vlog_profile_type_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationlog',
            index=models.Index(fields=['verification_type', 'result'], name='vlog_type_result_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['status'], name='vsession_status_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['user', 'status'], name='vsession_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['session_key'], name='vsession_session_key_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationsession',
            index=models.Index(fields=['expires_at'], name='vsession_expires_idx'),
        ),
    ]
