# Generated by Django 5.2.15 on 2026-07-03 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faceprofile',
            name='passport_embedding',
        ),
        migrations.RemoveField(
            model_name='faceprofile',
            name='passport_image',
        ),
        migrations.RemoveField(
            model_name='faceprofile',
            name='passport_image_hash',
        ),
    ]
