# Generated by Django 5.0.6 on 2026-06-24 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='e.g. AKHU2026-000001', max_length=50, unique=True, verbose_name='QR Token')),
                ('signed_token', models.TextField(blank=True, help_text='JWT-signed token for tamper detection', verbose_name='Signed JWT Token')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('applicant_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='accounts.applicantprofile')),
                ('last_scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QR Code',
                'verbose_name_plural': 'QR Codes',
                'ordering': ['-generated_at'],
            },
        ),
    ]
