# Generated by Django 5.0.6 on 2026-06-24 07:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('user_role_snapshot', models.CharField(blank=True, max_length=20)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('verification', 'Verification'), ('admin', 'Administration'), ('supervisor', 'Supervisor'), ('data', 'Data Management'), ('security', 'Security'), ('system', 'System'), ('report', 'Reports')], default='system', max_length=20)),
                ('action', models.CharField(max_length=200, verbose_name='Action')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['category', 'timestamp'], name='audit_audit_categor_c661fd_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_4a1174_idx')],
            },
        ),
    ]
